- name: play01
  hosts: frontend
  tasks: 
  - name : play01 and task01
      ansible.builtin.debug:
      msg: this is play01 and task01

  - name : play01 and task02
      ansible.builtin.debug:
      msg: this is play01 and task02  

  
- name: play02
  hosts: frontend
  tasks: 
  - name : play02 and task01
      ansible.builtin.debug:
      msg: this is play02 and task01

  - name : play02 and task02
      ansible.builtin.debug:
      msg: this is play02 and task02  