- name: variables script
  hosts: local
  connection: local
  vars:
    Course: Devops
    Duration: 120 days
    Trainer: Siva Kumar
  tasks:
    - name: Print variables
      ansible.builtin.debug:
      msg: "Course Name is {{ $Course }}, Course is trained by {{ $Duration }}, Duration is {{ Trainer }}"      