- name: variables script
  hosts: localhost
  connection: local
  vars:
  NAME: from play level variable
  vars_files:
  - course.yaml
  vars_prompt:
  - Name: NAME
    prompt: what is your NAME?
    private: false
  tasks:
  - name: testing variable preference
    vars:
      NAME: from play level variable
    ansible.builtin.debug:
      msg: "{{ NAME }}"