- name: condition playbook
  hosts: localhost
  connection: local
  vars:
    number: 12
  tasks: 
  - name: check given is less than or not
    ansible.builtin.debug:
      msg: "Given {{ number }} is less than 10".
    when: number < 10   