- name: user creation
  hosts: localhost
  connection: local 
  tasks:
  - name: check roboshop user
    ansible.builtin.shell: id roboshop
    register: user_check
    ignore_errors: true

  - name: print
    ansible.builtin.debug:
      msg: "{{ user_check }}"
  
  - name: create user
    ansible.builtin.shell: useradd roboshop
    when user_check.rc !=0